### ISSUE TITLE
OUT_OF_MEMORY

### ISSUE THREAD

**Issue by Xiao-R-Y** [jongdory/ALDM#4]
Thanks for your excellent work, I try to reimplement the code according to the instruction, but since the GPU is 24G, it still goes OOM after I decrease the num_works from 8 to 1. Could you please give me some suggestions on how to make it trainable on a 24G gpu card? Thanks a lot.

**Comment by jongdory** [comment]
For saving memory during VQGAN training, I recommend reducing the patch size to 96x96x96 or smaller.
During the training of the latent diffusion model, there is no need to reduce the patch size; it works well with 24GB of memory.

Thank you for your interest in our works
