### ISSUE TITLE
About the parameter: skip_pass

### ISSUE THREAD

**Issue by ge-xing** [jongdory/ALDM#6]
Thank you for your great work! I have observed that in vqgan model, self.loss function needs the skip_pass parameter:
<img width="804" alt="image" src="https://github.com/jongdory/ALDM/assets/109211094/99fb78fd-5da3-4599-90a7-c1b0d372d382">

However, in the loss function, the parameter seems to miss.

<img width="652" alt="image" src="https://github.com/jongdory/ALDM/assets/109211094/f690763c-9ffb-44c3-9f2e-74b9fa84fb81">

So now I get this error:
<img width="829" alt="image" src="https://github.com/jongdory/ALDM/assets/109211094/5af20c52-9088-4bbd-aebe-64df66a8d2d6">

**Comment by jongdory** [comment]
Thank you for your interest in our research!
We've just identified and fixed the code error.
It should work fine now. Thanks a lot.

**Comment by ge-xing** [comment]
Thank you very much!
